services:
  - type: web
    name: gileslamb-portfolio
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm install && npm run build
    startCommand: node node_modules/.bin/next start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
