"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import styles from "./listening-room.module.css";
import cues from "./cues.json";

/* Media lives in the music-releases R2 bucket under invisible-threads/ */
const R2_BASE =
  "https://pub-1c42ac5be9844cb9bd9cf16ce1ef9b94.r2.dev/invisible-threads/";
const VIDEO_SRC = `${R2_BASE}invisible-threads_listening-room_WEB_1440_h264.mp4`;
const STREAM_SRC = `${R2_BASE}invisible-threads_listening-room_STREAM_aac256.m4a`;

/* Printed cover (3000 px RGB), resized only */
const COVER_SRC = "/releases/invisible-threads/cover.jpg";
const COVER_THUMB_SRC = "/releases/invisible-threads/cover-thumb.jpg";

/* Listen / buy links. Bandcamp live 3 Sep 2026. When Spotify and Apple
   Music are live, set their URLs here and uncomment their rows in the
   buy block below the tracklist. */
const BANDCAMP_URL = "https://gileslamb.bandcamp.com/album/invisible-threads";
// const SPOTIFY_URL = "";
// const APPLE_MUSIC_URL = "";
/* Cancer Research UK donate link, confirmed by Giles 3 Sep 2026 */
const DONATE_URL = "https://www.cancerresearchuk.org/get-involved/donate";

/* Sleeve back: tracks marked * carry the cello credit */
const CELLO = new Set(["September", "Shimmering Thirds", "Lost"]);

/* Per-track start offsets in the single stream — generated by
   scripts/invisible-threads/cues.py, never hand-entered */
const CUES: { title: string; startSeconds: number }[] = cues;

function PlayIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path d="M8 5.5v13l10-6.5z" />
    </svg>
  );
}

function PauseIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path d="M7.5 5.5h3v13h-3zM13.5 5.5h3v13h-3z" />
    </svg>
  );
}

function trackAt(time: number): number {
  let i = -1;
  for (let k = 0; k < CUES.length; k++) {
    if (time + 0.05 >= CUES[k].startSeconds) i = k;
  }
  return i;
}

export default function InvisibleThreadsClient({
  fontClass,
}: {
  fontClass: string;
}) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const audioRef = useRef<HTMLAudioElement>(null);
  const pendingSeek = useRef<number | null>(null);
  const [playing, setPlaying] = useState(false);
  const [current, setCurrent] = useState(-1);

  /* Lock scroll for the full-viewport layout (same pattern as /urlar) */
  useEffect(() => {
    const prevBody = document.body.style.overflow;
    const prevHtml = document.documentElement.style.overflow;
    document.body.style.overflow = "hidden";
    document.documentElement.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = prevBody;
      document.documentElement.style.overflow = prevHtml;
    };
  }, []);

  /* React does not reliably emit the `muted` attribute on SSR output, and
     browsers only autoplay muted video — set it on the element directly. */
  useEffect(() => {
    const v = videoRef.current;
    if (!v) return;
    v.defaultMuted = true;
    v.muted = true;
    const tryPlay = () => {
      if (!v.paused) return;
      const p = v.play();
      if (p) p.catch(() => {});
    };
    tryPlay();
    const opts = { passive: true } as const;
    document.addEventListener("pointerdown", tryPlay, opts);
    document.addEventListener("keydown", tryPlay, opts);
    document.addEventListener("touchstart", tryPlay, opts);
    return () => {
      document.removeEventListener("pointerdown", tryPlay);
      document.removeEventListener("keydown", tryPlay);
      document.removeEventListener("touchstart", tryPlay);
    };
  }, []);

  /* Mirror the audio element's real state; derive the playing track from time */
  useEffect(() => {
    const a = audioRef.current;
    if (!a) return;
    const on = () => setPlaying(true);
    const off = () => setPlaying(false);
    const ended = () => {
      setPlaying(false);
      setCurrent(-1);
    };
    const tick = () => setCurrent(trackAt(a.currentTime));
    const meta = () => {
      if (pendingSeek.current !== null) {
        a.currentTime = pendingSeek.current;
        pendingSeek.current = null;
      }
    };
    a.addEventListener("play", on);
    a.addEventListener("pause", off);
    a.addEventListener("ended", ended);
    a.addEventListener("timeupdate", tick);
    a.addEventListener("seeked", tick);
    a.addEventListener("loadedmetadata", meta);
    return () => {
      a.removeEventListener("play", on);
      a.removeEventListener("pause", off);
      a.removeEventListener("ended", ended);
      a.removeEventListener("timeupdate", tick);
      a.removeEventListener("seeked", tick);
      a.removeEventListener("loadedmetadata", meta);
    };
  }, []);

  const wakeVideo = useCallback(() => {
    const v = videoRef.current;
    if (v && v.paused) {
      const p = v.play();
      if (p) p.catch(() => {});
    }
  }, []);

  const toggle = useCallback(() => {
    const a = audioRef.current;
    if (!a) return;
    wakeVideo();
    if (a.paused) {
      a.play().catch(() => {});
    } else {
      a.pause();
    }
  }, [wakeVideo]);

  /* The tracklist is the transport: seek the one stream to a track's offset */
  const seekTo = useCallback(
    (i: number) => {
      const a = audioRef.current;
      if (!a) return;
      wakeVideo();
      const t = CUES[i].startSeconds;
      if (a.readyState >= 1) {
        a.currentTime = t;
      } else {
        pendingSeek.current = t;
      }
      setCurrent(i);
      a.play().catch(() => {});
    },
    [wakeVideo],
  );

  return (
    <main className={`${styles.room} ${fontClass}`}>
      <video
        ref={videoRef}
        className={styles.video}
        src={VIDEO_SRC}
        autoPlay
        muted
        loop
        playsInline
        preload="auto"
        disablePictureInPicture
        disableRemotePlayback
        aria-hidden="true"
        tabIndex={-1}
      />
      <div className={styles.scrim} aria-hidden="true" />

      {/* Opening anchor: the printed cover, held, then dissolved into the film */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        className={styles.coverFull}
        src={COVER_SRC}
        alt=""
        aria-hidden="true"
        decoding="async"
        fetchPriority="high"
      />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        className={styles.coverSmall}
        src={COVER_THUMB_SRC}
        alt="Invisible Threads — Giles Lamb, printed cover"
        decoding="async"
      />

      {/* Way back to the releases index: beside the small cover, settles in with it */}
      <Link href="/releases" className={styles.back}>
        ← Releases
      </Link>

      <audio ref={audioRef} src={STREAM_SRC} preload="metadata" />

      <div className={styles.text}>
        <p className={styles.artist}>Giles Lamb</p>
        <h1 className={styles.title}>Invisible Threads</h1>
        <button
          type="button"
          className={styles.play}
          onClick={toggle}
          aria-label={playing ? "Pause" : "Play"}
          aria-pressed={playing}
        >
          {playing ? <PauseIcon /> : <PlayIcon />}
        </button>
      </div>

      {/* Sleeve text, in sleeve order; the tracklist is the player control */}
      <aside className={styles.sleeve} aria-label="Sleeve">
        <p className={styles.liner}>
          Music has been my guide through grief. The first of these pieces was
          written in 1993, the year my mother died. The rest followed over
          thirty years. She was full of joy, so this is not a sad record. It is
          a thank-you.
        </p>
        <p className={styles.dedication}>For Jill, Richard and Nick</p>

        <ol className={styles.tracks}>
          {CUES.map((c, i) => (
            <li key={c.title}>
              <button
                type="button"
                className={`${styles.track} ${i === current ? styles.trackOn : ""}`}
                onClick={() => seekTo(i)}
                aria-current={i === current ? "true" : undefined}
                aria-label={`${i + 1}. ${c.title}${CELLO.has(c.title) ? ", cello Peter Nicholson" : ""}`}
              >
                <span className={styles.num} aria-hidden="true">
                  {i + 1}
                </span>
                <span className={styles.trackTitle}>
                  {c.title}
                  {CELLO.has(c.title) ? " *" : ""}
                </span>
              </button>
            </li>
          ))}
        </ol>

        {/* Listen / buy — Bandcamp now; Spotify and Apple Music slot in beneath */}
        <div className={styles.buy}>
          <ul className={styles.buyLinks}>
            <li>
              <a href={BANDCAMP_URL} target="_blank" rel="noopener noreferrer">
                Buy the album on Bandcamp
              </a>
            </li>
            {/* <li>
              <a href={SPOTIFY_URL} target="_blank" rel="noopener noreferrer">
                Listen on Spotify
              </a>
            </li> */}
            {/* <li>
              <a href={APPLE_MUSIC_URL} target="_blank" rel="noopener noreferrer">
                Listen on Apple Music
              </a>
            </li> */}
          </ul>
          <p className={styles.buyNote}>
            All proceeds to Cancer Research UK. Limited CD available.
          </p>
        </div>

        <p className={styles.credit}>Written, composed and performed by Giles Lamb</p>
        <p className={styles.credit}>* Cello, Peter Nicholson</p>

        <p className={styles.rights}>
          P &amp; C 2026 Giles Lamb<span className={styles.dash}>-</span>All rights
          reserved
        </p>
        <p className={styles.profits}>
          <a href={DONATE_URL} target="_blank" rel="noopener noreferrer">
            All profits to Cancer Research UK
          </a>
        </p>
      </aside>
    </main>
  );
}
